require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance
  - rubocop-thread_safety

# Enable newly released Rubocop cops.
AllCops:
  NewCops: enable

Style/SymbolArray:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Rails/FilePath:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
